export const KNOWN_SERVICES = [
  {
    id: 'YOUTUBE_PREMIUM',
    name: 'YouTube Premium',
    iconUrl: '/images/logo/youtube-icon.svg',
    textUrl: '/images/logo/youtube-text.svg',
  },
  {
    id: 'NETFLIX',
    name: 'Netflix',
    iconUrl: '/images/logo/netflix-icon.svg',
    textUrl: '/images/logo/netflix-text.svg',
  },
  {
    id: 'SPOTIFY',
    name: 'Spotify',
    iconUrl: '/images/logo/spotify-icon.svg',
    textUrl: '/images/logo/spotify-text.svg',
  },
  {
    id: 'APPLE_MUSIC',
    name: 'Apple Music',
    iconUrl: '/images/logo/apple-music-icon.svg',
    textUrl: '/images/logo/apple-music-text.svg',
  },
  {
    id: 'COUPANG_WOW',
    name: 'Coupang Wow',
    iconUrl: '/images/logo/coupang-icon.svg',
    textUrl: '/images/logo/coupang-text.svg',
  },
  {
    id: 'WAVVE',
    name: 'Wavve',
    iconUrl: '/images/logo/wavve-icon.svg',
    textUrl: '/images/logo/wavve-text.svg',
  },
  {
    id: 'WATCHA',
    name: 'Watcha',
    iconUrl: '/images/logo/watcha-icon.svg',
    textUrl: '/images/logo/watcha-text.svg',
  },
  {
    id: 'TVING',
    name: 'Tving',
    iconUrl: '/images/logo/tving-icon.svg',
    textUrl: '/images/logo/tving-text.svg',
  },
  {
    id: 'DISNEY_PLUS',
    name: 'Disney Plus',
    iconUrl: '/images/logo/disney-plus-icon.svg',
    textUrl: '/images/logo/disney-plus-text.svg',
  },
  {
    id: 'APPLE_TV',
    name: 'Apple TV+',
    iconUrl: '/images/logo/apple-tv-icon.svg',
    textUrl: '/images/logo/apple-tv-text.svg',
  },
  {
    id: 'LAFTEL',
    name: 'Laftel',
    iconUrl: '/images/logo/laftel-icon.svg',
    textUrl: '/images/logo/laftel-text.svg',
  },
  {
    id: 'MELON',
    name: 'Melon',
    iconUrl: '/images/logo/melon-icon.svg',
    textUrl: '/images/logo/melon-text.svg',
  },
  {
    id: 'GENIE',
    name: 'Genie',
    iconUrl: '/images/logo/genie-icon.svg',
    textUrl: '/images/logo/genie-text.svg',
  },
  {
    id: 'FLO',
    name: 'Flo',
    iconUrl: '/images/logo/flo-icon.svg',
    textUrl: '/images/logo/flo-text.svg',
  },
  {
    id: 'AWS',
    name: 'Amazon Web Service',
    iconUrl: '/images/logo/aws-icon.svg',
    textUrl: '/images/logo/aws-text.svg',
  },
  {
    id: 'GCP',
    name: 'Google Cloud Platform',
    iconUrl: '/images/logo/gcp-icon.svg',
    textUrl: '/images/logo/gcp-text.svg',
  },
  {
    id: 'CHAT_GPT',
    name: 'ChatGPT',
    iconUrl: '/images/logo/chatgpt-icon.svg',
    textUrl: '/images/logo/chatgpt-text.svg',
  },
  {
    id: 'CLAUDE_AI',
    name: 'Claude AI',
    iconUrl: '/images/logo/claude-ai-icon.svg',
    textUrl: '/images/logo/claude-ai-text.svg',
  },
  {
    id: 'GEMINI',
    name: 'Gemini',
    iconUrl: '/images/logo/gemini-icon.svg',
    textUrl: '/images/logo/gemini-text.svg',
  },
  {
    id: 'PERPLEXITY',
    name: 'Perplexity',
    iconUrl: '/images/logo/perplexity-icon.svg',
    textUrl: '/images/logo/perplexity-text.svg',
  },
  {
    id: 'SPOTV_NOW',
    name: 'SPOTV Now',
    iconUrl: '/images/logo/spotv-now-icon.svg',
    textUrl: '/images/logo/spotv-now-text.svg',
  },
]