export const KNOWN_SERVICES = [
  {
    id: 'youtube',
    name: 'YouTube Premium',
    iconUrl: '/images/logo/youtube-icon.svg',
    textUrl: '/images/logo/youtube-text.svg',
  },
  {
    id: 'netflix',
    name: 'Netflix',
    iconUrl: '/images/logo/netflix-icon.svg',
    textUrl: '/images/logo/netflix-text.svg',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    iconUrl: '/images/logo/spotify-icon.svg',
    textUrl: '/images/logo/spotify-text.svg',
  },
  {
    id: 'apple-music',
    name: 'Apple Music',
    iconUrl: '/images/logo/apple-music-icon.svg',
    textUrl: '/images/logo/apple-music-text.svg',
  },
  {
    id: 'coupang',
    name: 'Coupang Wow',
    iconUrl: '/images/logo/coupang-icon.svg',
    textUrl: '/images/logo/coupang-text.svg',
  },
  {
    id: 'wave',
    name: 'Wavve',
    iconUrl: '/images/logo/wavve-icon.svg',
    textUrl: '/images/logo/wavve-text.svg',
  },
  {
    id: 'watcha',
    name: 'Watcha',
    iconUrl: '/images/logo/watcha-icon.svg',
    textUrl: '/images/logo/watcha-text.svg',
  },
  {
    id: 'tving',
    name: 'Tving',
    iconUrl: '/images/logo/tving-icon.svg',
    textUrl: '/images/logo/tving-text.svg',
  },
  {
    id: 'disney-plus',
    name: 'Disney Plus',
    iconUrl: '/images/logo/disney-plus-icon.svg',
    textUrl: '/images/logo/disney-plus-text.svg',
  },
  {
    id: 'apple-tv',
    name: 'Apple TV+',
    iconUrl: '/images/logo/apple-tv-icon.svg',
    textUrl: '/images/logo/apple-tv-text.svg',
  },
  {
    id: 'lattel',
    name: 'Laftel',
    iconUrl: '/images/logo/laftel-icon.svg',
    textUrl: '/images/logo/laftel-text.svg',
  },
  {
    id: 'melon',
    name: 'Melon',
    iconUrl: '/images/logo/melon-icon.svg',
    textUrl: '/images/logo/melon-text.svg',
  },
  {
    id: 'genie',
    name: 'Genie',
    iconUrl: '/images/logo/genie-icon.svg',
    textUrl: '/images/logo/genie-text.svg',
  },
  {
    id: 'flo',
    name: 'Flo',
    iconUrl: '/images/logo/flo-icon.svg',
    textUrl: '/images/logo/flo-text.svg',
  },
  {
    id: 'aws',
    name: 'Amazon Web Service',
    iconUrl: '/images/logo/aws-icon.svg',
    textUrl: '/images/logo/aws-text.svg',
  },
  {
    id: 'gcp',
    name: 'Google Cloud Platform',
    iconUrl: '/images/logo/gcp-icon.svg',
    textUrl: '/images/logo/gcp-text.svg',
  },
  {
    id: 'claude-ai',
    name: 'Claude AI',
    iconUrl: '/images/logo/claude-ai-icon.svg',
    textUrl: '/images/logo/claude-ai-text.svg',
  },
  {
    id: 'chat-gpt',
    name: 'ChatGPT',
    iconUrl: '/images/logo/chatgpt-icon.svg',
    textUrl: '/images/logo/chatgpt-text.svg',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    iconUrl: '/images/logo/perplexity-icon.svg',
    textUrl: '/images/logo/perplexity-text.svg',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    iconUrl: '/images/logo/gemini-icon.svg',
    textUrl: '/images/logo/gemini-text.svg',
  },
  {
    id: 'spotv-now',
    name: 'SPOTV Now',
    iconUrl: '/images/logo/spotv-now-icon.svg',
    textUrl: '/images/logo/spotv-now-text.svg',
  },
]
